"""
config/settings.py
All configuration read from environment variables.
Copy .env.example to .env for local dev.
"""

import os

# ── Core ────────────────────────────────────────────────────────────────────

# Set this to your Railway URL after first deploy, e.g. https://inroad.up.railway.app
APP_BASE_URL = os.environ.get("APP_BASE_URL", "http://localhost:5001").rstrip("/")

SESSION_SECRET = os.environ.get(
    "SESSION_SECRET",
    "change-me-in-production-use-a-long-random-string"
)

# ── Email (Resend / SMTP) ───────────────────────────────────────────────────

RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
SMTP_HOST      = os.environ.get("SMTP_HOST", "smtp.resend.com")
SMTP_PORT      = int(os.environ.get("SMTP_PORT", "465"))
SMTP_USER      = os.environ.get("SMTP_USER", "resend")
SMTP_PASS      = os.environ.get("SMTP_PASS", "")
FROM_EMAIL     = os.environ.get("FROM_EMAIL", "noreply@signin.the-inroad.com")
FROM_NAME      = os.environ.get("FROM_NAME", "inroad")

# ── APIs ────────────────────────────────────────────────────────────────────

SERPER_API_KEY = os.environ.get("SERPER_API_KEY", "")
APOLLO_API_KEY = os.environ.get("APOLLO_API_KEY", "")
PDL_API_KEY    = os.environ.get("PDL_API_KEY", "")

# ── Token / session config ──────────────────────────────────────────────────

MAGIC_LINK_EXPIRY_MINUTES = int(os.environ.get("MAGIC_LINK_EXPIRY_MINUTES", "30"))
MAGIC_LINK_RATE_LIMIT     = int(os.environ.get("MAGIC_LINK_RATE_LIMIT", "3"))
MAGIC_LINK_RATE_WINDOW    = int(os.environ.get("MAGIC_LINK_RATE_WINDOW", "10"))  # minutes

SESSION_DAYS = int(os.environ.get("SESSION_DAYS", "30"))

JWT_SECRET = os.environ.get("JWT_SECRET", "change-jwt-secret-in-production")
JWT_ACCESS_TTL_MINUTES = int(os.environ.get("JWT_ACCESS_TTL_MINUTES", "1440"))
JWT_REFRESH_TTL_DAYS = int(os.environ.get("JWT_REFRESH_TTL_DAYS", "30"))

# ── CORS ────────────────────────────────────────────────────────────────────

# Comma-separated list of allowed origins, e.g. https://coffeechatconnect.com
ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get("ALLOWED_ORIGINS", "http://localhost:5001,http://127.0.0.1:5001").split(",")
    if o.strip()
]

# ── Feature flags ───────────────────────────────────────────────────────────

DEV_MODE             = os.environ.get("DEV_MODE",             "false").lower() == "true"
SEARCH_ROLES_ENABLED = os.environ.get("SEARCH_ROLES_ENABLED", "false").lower() == "true"
SEND_DAILY_EMAILS    = os.environ.get("SEND_DAILY_EMAILS",    "false").lower() == "true"

ADMIN_SECRET = os.environ.get("ADMIN_SECRET", "")

# ── Microsoft / Outlook OAuth ─────────────────────────────────────────────────

AZURE_CLIENT_ID     = os.environ.get("AZURE_CLIENT_ID", "")
AZURE_CLIENT_SECRET = os.environ.get("AZURE_CLIENT_SECRET", "")

# ── Pipeline ─────────────────────────────────────────────────────────────────

DAILY_MATCH_QUOTA   = int(os.environ.get("DAILY_MATCH_QUOTA",   "3"))
CLOSING_SOON_DAYS   = int(os.environ.get("CLOSING_SOON_DAYS",   "7"))
FRESHNESS_DECAY_DAYS = int(os.environ.get("FRESHNESS_DECAY_DAYS", "30"))

# Path to the SQLite database (ignored when DATABASE_URL is set)
DB_PATH = os.environ.get("DB_PATH", "")

# ── Scraper / pipeline constants ──────────────────────────────────────────────

REQUEST_DELAY_SECONDS = float(os.environ.get("REQUEST_DELAY_SECONDS", "1.0"))
REQUEST_TIMEOUT       = int(os.environ.get("REQUEST_TIMEOUT", "15"))
MAX_RETRIES           = int(os.environ.get("MAX_RETRIES", "3"))

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
]

SENIORITY_KEYWORDS = {
    "intern":     ["intern", "internship", "placement", "summer analyst", "spring week"],
    "junior":     ["junior", "graduate", "grad", "entry level", "new grad", "trainee"],
    "mid":        ["analyst", "specialist", "engineer", "consultant", "advisor"],
    "senior":     ["senior", "lead", "principal", "staff", "experienced"],
    "leadership": ["manager", "director", "vp", "vice president", "head of", "partner",
                   "managing director", "md", "chief"],
}

INDUSTRIES = [
    "Finance", "Investment Banking", "Software Engineering", "Technology",
    "Product Management", "Consulting", "Strategy", "Marketing",
    "Law", "Healthcare", "Media & Journalism",
    "Data & Analytics", "Real Estate", "Non-profit & Policy",
    "Other",
]

# ── Lead pre-fetch: company size lookup ──────────────────────────────────────

COMPANY_SIZE_LOOKUP = {
    # ── Bulge bracket banks ───────────────────────────────────────────────────
    "goldman sachs": "large", "jp morgan": "large", "jpmorgan": "large",
    "j.p. morgan": "large", "morgan stanley": "large", "barclays": "large",
    "hsbc": "large", "blackrock": "large", "ubs": "large",
    "deutsche bank": "large", "citi": "large", "citigroup": "large",
    "citibank": "large", "bank of america": "large", "bnp paribas": "large",
    "société générale": "large", "societe generale": "large",
    "nomura": "large", "macquarie": "large", "macquarie group": "large",
    "credit suisse": "large", "mufg": "large", "smbc": "large",
    "mizuho": "large", "santander": "large", "rabobank": "large",
    "standard chartered": "large", "lloyds banking group": "large",
    "natwest markets": "large", "natwest": "large",
    "bank of england": "large", "commerzbank": "large",
    "ing": "large", "abn amro": "large", "intesa sanpaolo": "large",
    "crédit agricole": "large", "credit agricole": "large",
    "natixis": "large", "bbva": "large", "scotiabank": "large",
    "bmo capital markets": "large", "rbc capital markets": "large",
    "cibc": "large", "td securities": "large", "td cowen": "large",
    "btg pactual": "large", "icbc standard bank": "large",
    "bank of china": "large", "cicc": "large", "citic clsa": "large",
    # ── Elite boutiques ───────────────────────────────────────────────────────
    "lazard": "mid", "lazard asset management": "mid",
    "rothschild": "mid", "rothschild & co": "mid", "rothschild & co.": "mid",
    "evercore": "mid", "moelis": "mid", "moelis & company": "mid",
    "moelis & co": "mid", "pjt partners": "mid",
    "centerview partners": "mid", "perella weinberg partners": "mid",
    "greenhill": "mid", "houlihan lokey": "mid",
    "jefferies": "mid", "lincoln international": "mid",
    "baird": "mid", "william blair": "mid", "stifel": "mid",
    "raymond james": "mid", "stephens": "mid",
    "piper sandler": "mid", "canaccord genuity": "mid",
    "oppenheimer & co": "mid", "wedbush securities": "mid",
    "harris williams": "mid", "dc advisory": "mid",
    "raine group": "mid", "liontree": "mid", "torch partners": "mid",
    "arma partners": "mid", "fenchurch advisory": "mid",
    "gleacher shacklock": "mid", "hannam & partners": "mid",
    "panmure liberum": "mid", "peel hunt": "mid", "berenberg": "mid",
    "numis": "mid", "investec": "mid",
    "stout": "mid", "stax": "mid", "solomon partners": "mid",
    # ── Asset management ──────────────────────────────────────────────────────
    "bridgewater associates": "large", "man group": "large",
    "wellington management": "large", "t. rowe price": "large",
    "t rowe price": "large", "fidelity investments": "large",
    "fidelity international": "large",
    "franklin templeton": "large", "vanguard": "large",
    "invesco": "large", "schroders": "large", "aberdeen group": "large",
    "abrdn": "large", "columbia threadneedle investments": "large",
    "pgim": "large", "pimco": "large", "nuveen": "large",
    "legal & general": "large", "aviva investors": "large",
    "axa investment managers": "large", "dws": "large",
    "m&g": "large", "neuberger berman": "large",
    "alliancebernstein": "large", "principal asset management": "large",
    "state street": "large", "bny mellon": "large",
    "northern trust": "large", "charles schwab": "large",
    "blackstone": "large", "kkr": "large", "carlyle": "large",
    "the carlyle group": "large", "apollo global management": "large",
    "ares management": "large", "tpg": "large",
    "brookfield": "large", "hamilton lane": "large",
    "harbourvest": "mid", "stepstone group": "mid",
    "partners group": "large", "ardian": "large",
    "pantheon capital management": "mid",
    "cambridge associates": "mid", "gresham investment management": "mid",
    "impax asset management": "mid", "ninety one": "mid",
    "sands capital": "mid", "brown advisory": "mid",
    "orbis": "mid", "dodge & cox": "mid", "harris associates": "mid",
    "dimensional fund advisors": "mid", "mfs": "mid",
    "putnam": "mid", "tcw": "mid", "robeco": "mid",
    "pictet asset management": "mid", "julius baer": "mid",
    "balyasny asset management": "mid", "marshall wace": "mid",
    "bluecrest capital management": "mid", "brevan howard": "mid",
    "rokos capital management": "mid", "capula investment management": "mid",
    "gsa capital": "mid", "g-research": "mid", "quadrature": "mid",
    "point72": "mid", "millennium management": "large",
    "schonfeld": "mid", "exoduspoint": "mid",
    "sculptor capital management": "mid", "soros fund management": "mid",
    "tudor group": "mid", "caxton associates": "mid",
    "aqr capital management": "mid", "two sigma": "mid",
    "citadel": "large", "citadel securities": "large",
    "jane street": "large", "optiver": "large", "flow traders": "mid",
    "imc trading": "mid", "akuna capital": "mid", "drw": "mid",
    "jump trading": "mid", "da vinci trading": "startup",
    "tower research capital": "mid", "hudson river trading": "mid",
    "virtu financial": "mid", "susquehanna international group": "large",
    "xtz markets": "mid", "xtx markets": "mid", "qube rt": "mid",
    "wintermute": "startup", "b2c2": "startup", "flowdesk": "startup",
    "marvel": "mid",  # note: Marex
    "marex": "mid", "marex spectron": "mid",
    "mckinsey": "large", "mckinsey & company": "large",
    # ── Private equity ────────────────────────────────────────────────────────
    "bain capital": "large", "tpg capital": "large",
    "advent international": "mid", "cinven": "mid",
    "cvc": "mid", "apax partners": "mid",
    "warburg pincus": "large", "general atlantic": "mid",
    "vista equity partners": "mid", "francisco partners": "mid",
    "silver lake": "large", "thoma bravo": "mid",
    "insight partners": "large", "tiger global": "mid",
    "summit partners": "mid", "llr partners": "mid",
    "gtcr": "mid", "roark capital group": "mid",
    "h.i.g. capital": "mid", "k1 investment management": "mid",
    "cd&r": "mid", "stone point capital": "mid",
    "towerbrook capital partners": "mid", "bridgepoint": "mid",
    "nordic capital": "mid", "triton": "mid",
    "ik partners": "mid", "equistone": "mid",
    "waterland private equity": "mid", "pai partners": "mid",
    "cerberus capital management": "large",
    "oaktree capital management": "large", "blue owl capital": "large",
    "sixth street": "mid", "psg equity": "mid",
    "eurazeo": "large", "tikehau capital": "mid",
    "hayfin capital management": "mid", "kartesia": "startup",
    "antin infrastructure partners": "mid", "infrared capital partners": "mid",
    "arcus infrastructure partners": "mid",
    "access holdings": "startup", "access capital partners": "startup",
    "alpine investors": "mid", "audax group": "mid",
    "nonantum capital partners": "startup",
    "17capital": "mid", "lgt capital partners": "mid",
    "mubadala capital": "large", "gic": "large", "temasek": "large",
    "cdpq": "large", "australiansuper": "large", "psp investments": "large",
    "norges bank": "large", "lothian pension fund": "mid",
    "uss": "mid", "lgt": "large", "lgt wealth management": "mid",
    # ── Big 4 / consulting ────────────────────────────────────────────────────
    "deloitte": "large", "pwc": "large", "kpmg": "large", "ey": "large",
    "ernst & young": "large", "ey-parthenon": "large",
    "bcg": "large", "boston consulting group": "large",
    "bain & company": "large", "oliver wyman": "large",
    "roland berger": "large", "arthur d. little": "mid",
    "kearney": "large", "l.e.k. consulting": "mid",
    "simon-kucher": "mid", "oc&c": "mid",
    "pa consulting": "mid", "fp": "mid", "fti consulting": "large",
    "alvarez & marsal": "mid", "alixpartners": "mid",
    "kroll": "mid", "berkley research group": "mid",
    "charles river associates": "mid", "brg": "mid",
    "compass lexecon": "mid", "oxera": "mid", "frontier economics": "mid",
    "cornerstone research": "mid", "the brattle group": "mid",
    "nera": "mid", "analysis group": "mid",
    "turner & townsend": "large", "arcadis": "large",
    "jacobs": "large", "wood mackenzie": "mid",
    "rystad energy": "mid", "ihs markit": "large",
    "gartner": "large", "forrester": "mid",
    "guidehouse": "mid", "protiviti": "large",
    "nextwave consulting": "startup",
    "baringa": "mid", "alpha fmc": "mid",
    "q5 partners": "startup", "strategy&": "large",
    # ── Law firms ─────────────────────────────────────────────────────────────
    "clifford chance": "large", "freshfields": "large",
    "freshfields bruckhaus deringer": "large",
    "linklaters": "large", "allen & overy": "large",
    "a&o shearman": "large", "a&o": "large",
    "slaughter and may": "large", "herbert smith freehills": "large",
    "hsf": "large", "hogan lovells": "large", "baker mckenzie": "large",
    "latham & watkins": "large", "sullivan & cromwell": "large",
    "kirkland & ellis": "large", "white & case": "large",
    "skadden": "large", "skadden arps": "large",
    "norton rose fulbright": "large", "dentons": "large",
    "clyde & co": "large", "cms": "large",
    "ashurst": "large", "eversheds sutherland": "large",
    "bird & bird": "large", "fieldfisher": "mid",
    "simmons & simmons": "mid", "travers smith": "mid",
    "macfarlanes": "mid", "charles russell speechlys": "mid",
    "stephenson harwood": "mid", "osborne clarke": "mid",
    "pinsent masons": "large", "shoosmiths": "mid",
    "browne jacobson": "mid", "weightmans": "mid",
    "squire patton boggs": "large", "mayer brown": "large",
    "paul hastings": "large", "greenberg traurig": "large",
    "fried frank": "mid", "gibson dunn": "large",
    "dechert llp": "large", "goodwin": "large",
    "morgan lewis": "large", "mcguirewoods": "mid",
    "arnold & porter": "large", "bryan cave leighton paisner": "large",
    "addleshaw goddard": "mid", "gowling wlg": "large",
    "burges salmon": "mid", "foot anstey": "mid",
    "trowers & hamlins": "mid", "mills & co": "mid",
    "gateley": "mid", "shakespeare martineau": "mid",
    "womble bond dickinson": "mid", "tlt": "mid",
    "michelmores": "mid", "forsters": "mid",
    "farrer & co": "mid", "payne hicks beach": "startup",
    "withers": "mid", "irwin mitchell": "large",
    "hill dickinson": "mid", "hfw": "mid",
    "watson farley & williams": "mid", "wallker morris": "mid",
    "walker morris": "mid", "dwf": "large",
    "rpc": "mid", "lewis silkin": "mid",
    "lge": "mid", "kennedys": "mid",
    "peters & peters": "startup", "bristows": "mid",
    # ── Tech ──────────────────────────────────────────────────────────────────
    "google": "large", "amazon": "large", "microsoft": "large",
    "meta": "large", "apple": "large", "salesforce": "large",
    "bloomberg": "large", "databricks": "mid", "snowflake": "mid",
    "palantir": "mid", "amd": "large", "arm": "large", "nvidia": "large",
    "qualcomm": "large", "intel": "large", "cisco": "large",
    "oracle": "large", "ibm": "large", "sap": "large",
    "autodesk": "large", "ebay": "large", "uber": "large",
    "netflix": "large", "spotify": "mid", "snap": "mid",
    "tiktok": "large", "tencent": "large",
    "cloudflare": "mid", "crowdstrike": "mid", "splunk": "mid",
    "pagerduty": "mid", "datadog": "mid", "mongodb": "mid",
    "confluent": "mid", "hashicorp": "mid", "gitlab": "mid",
    "jetbrains": "mid", "figma": "mid", "canva": "mid",
    "squarespace": "mid", "hubspot": "large",
    "zendesk": "large", "twilio": "mid", "sendgrid": "mid",
    "stripe": "mid", "adyen": "mid", "checkout.com": "mid",
    "revolut": "mid", "monzo": "mid", "wise": "mid",
    "starling bank": "mid", "oaknorth": "mid",
    "deepmind": "mid", "openai": "mid", "anthropic": "startup",
    "perplexity": "startup", "bending spoons": "startup",
    "deliveroo": "mid", "ocado group": "large",
    "bae systems": "large", "rolls-royce": "large",
    "airbus": "large", "thales": "large", "leonardo": "large",
    "ge": "large", "general electric": "large",
    "siemens": "large", "abb": "large",
    "astrazeneca": "large", "gsk": "large",
    "johnson & johnson": "large", "pfizer": "large",
    "bristol myers squibb": "large",
    "bp": "large", "shell": "large", "equinor": "large",
    "exxonmobil": "large", "rwe": "large", "e.on": "large",
    "national gas": "large", "national grid": "large",
    "bt": "large", "sky": "large", "vodafone": "large",
    "motorola solutions": "large", "keysight": "large",
    "f5": "large", "nutanix": "large", "te connectivity": "large",
    "viasat": "large", "ciena": "large", "viator": "mid",
    "waters corporation": "large", "pexip": "mid",
    "aveva": "large", "factset": "mid", "msci": "mid",
    "s&p global": "large", "moody's": "large",
    "fitch ratings": "mid", "london stock exchange group": "large",
    "lseg": "large", "cboe global markets": "large",
    "tradeweb": "mid", "cme group": "large", "ice": "large",
    "nasdaq": "large", "marketaxess": "mid",
    "bg group": "mid", "bpost": "mid",
    "mastercard": "large", "visa": "large", "paypal": "large",
    "american express": "large", "capital one": "large",
    "citizens financial group": "large",
    "huntington national bank": "mid",
    "texas capital bank": "mid", "firstbank": "mid",
    "five rings": "mid", "imc trading": "mid",
    "mako trading": "startup",
    # ── Accountancy / advisory ────────────────────────────────────────────────
    "grant thornton": "large", "rsmuk": "large", "rsm": "large",
    "rsm us": "large", "bdo global": "large", "bdo": "large",
    "forvis mazars": "large", "mazars": "large",
    "pkf littlejohn": "mid", "saffery": "mid",
    "haysmacintyre": "mid", "crowe": "large",
    "menzies": "mid", "johnston carmichael": "mid",
    "isio": "mid", "lcpq": "mid", "lcp": "mid",
    "barnett waddingham": "mid", "hymans robertson": "mid",
    "first actuarial": "mid", "mercer": "large", "wtwl": "large",
    "wtw": "large", "aon": "large", "marsh mclennan": "large",
    "lockton": "mid", "howden": "mid", "guy carpenter": "large",
    "swiss re": "large", "munich re": "large",
    "zurich insurance": "large", "hiscox": "mid",
    "convex insurance": "startup", "allied world": "mid",
    "markel": "mid", "ryan specialty": "mid",
    "hamilton insurance group": "mid",
    # ── Real estate ───────────────────────────────────────────────────────────
    "jll": "large", "cbre": "large", "cushman & wakefield": "large",
    "knight frank": "large", "savills": "large",
    "colliers": "large", "eastdil secured": "mid",
    "lasalle": "large", "brookfield": "large",
    "greystar": "large", "hines": "large",
    "nuveen": "large", "tishman speyer": "large",
    "starwood capital group": "mid", "british land": "large",
    "canary wharf group": "mid", "related argent": "mid",
    "northwood investors": "mid", "harrison street": "mid",
    "cabot properties": "mid", "w. p. carey": "large",
    "welltower": "large", "altus group": "mid",
    "carter jonas": "mid", "activumsg": "startup",
    # ── Financial services / insurance ────────────────────────────────────────
    "hargreaves lansdown": "large", "st james's place": "large",
    "evelyn partners": "large", "quilter": "large",
    "royal london": "large", "legal & general": "large",
    "nationwide": "large", "lloyds banking group": "large",
    "canada life": "large", "phoenix group": "large",
    "pension insurance corporation": "mid",
    "rothesay": "mid", "just": "mid",
    "brown shipley": "mid", "coutts": "mid",
    "weatherbys private bank": "startup",
    "arbuthnot latham": "mid", "handelsbanken": "large",
    "aj bell": "mid", "hargreaves lansdown": "large",
    "interactive investor": "mid", "moneysupermarket": "mid",
    "compare the market": "large",
    "burford capital": "mid", "ithaca energy": "mid",
    "7im": "mid", "aberdeen group": "large",
    "allianz global investors": "large", "allianz insurance": "large",
    "baillie gifford": "mid", "caledonia investments": "mid",
    "charles taylor": "mid", "ageas": "large",
    "aegon": "large",
    # ── Misc / multi-sector ───────────────────────────────────────────────────
    "ibm": "large", "accenture": "large", "capgemini": "large",
    "infosys": "large", "wipfli": "large", "wipro": "large",
    "tata consultancy services": "large", "tcs": "large",
    "hp": "large", "lenovo": "large", "nxp semiconductors": "large",
    "astrazeneca": "large", "pfizer": "large", "merck": "large",
    "abbvie": "large", "novartis": "large", "roche": "large",
    "l'oréal": "large", "loreal": "large",
    "p&g": "large", "unilever": "large",
    "red bull": "large", "tesco": "large", "sainsbury's": "large",
    "marriott international": "large", "hilton": "large",
    "british airways": "large", "eurostar": "large",
    "network rail": "large", "national highways": "large",
    "severn trent": "large", "centrica": "large",
    "national audit office": "large",
    "financial conduct authority": "large", "ebrd": "large",
    "uk atomic energy authority": "mid",
    "police scotland": "large",
    "trainline": "mid", "dojo": "startup",
    "dunelm": "large", "ocado group": "large",
    "sky": "large", "universal music group": "large",
    "the economist": "mid", "financial times": "large",
    "the wall street journal": "large",
    "warner bros. discovery": "large",
    "the walt disney company": "large",
    "dow jones": "large", "bloomberg": "large",
    "pitchbook": "mid", "preqin": "mid",
    "verisk": "large", "ihs markit": "large",
    "epic games": "large", "ubisoft": "large",
    "niantic": "mid", "king": "large",
    "roku": "mid", "the trade desk": "mid",
    "squarepoint capital": "mid",
    "glg": "mid", "alphasights": "mid",
    "teneo": "mid",
    "coinbase": "mid", "ripple": "startup",
    "blockchain.com": "startup", "copper.co": "startup",
}


# ── Lead pre-fetch: title → department mapping ────────────────────────────────
# Ordered list — first matching entry wins. Check most-specific patterns first.

TITLE_DEPT_MAP = [
    # Investment banking / M&A (check before generic "invest")
    (["investment banking", "m&a", "mergers", "dcm", "ecm", "leveraged finance",
      "capital markets", "fig ", "debt advisory", "restructuring", "ipo",
      "equity capital", "debt capital", "advisory intern", "ib analyst",
      "ib associate", "corporate finance",
      "global advisory", "strategic advisory", "advisory"], "investment_banking"),
    # Quant (before sales_trading — "quant trader" should map here not sales_trading)
    (["quantitative", "quant trader", "quant research", "quant analyst",
      "quant intern", "strat intern", "structur"], "quant"),
    # Sales & trading / markets
    (["sales trading", "sales & trading", "fixed income", "derivatives",
      "fx trading", "equity sales", "trader", "markets intern", "trading intern",
      "flow trading", "market making"], "sales_trading"),
    # Healthcare / Life Sciences (before equity_research — "clinical research" must not map there)
    (["life sciences", "clinical research", "pharmaceutical", "pharma", "biotech",
      "biotechnology", "medical devices", "health economics", "healthcare analyst",
      "clinical data", "clinical trial"], "healthcare"),
    # Equity research
    (["equity research", "research analyst", "sell-side", "research associate",
      "equity analyst"], "equity_research"),
    # Risk
    (["risk analyst", "risk manag", "credit risk", "market risk",
      "operational risk", "risk intern", "actuarial", "actuary"], "risk"),
    # Asset / wealth / portfolio / PE / VC / real estate
    (["asset management", "portfolio manag", "wealth manag", "fund manag",
      "investment manag", "private equity", "pe intern", "buyout",
      "venture capital", "vc intern", "real estate invest", "property invest",
      "real estate", "property invest", "real assets",
      "credit invest", "special situations", "private credit",
      "infrastructure invest", "private markets",
      "investor relations", "clean energy", "renewable energy",
      "infrastructure fund"], "asset_management"),
    # Software engineering (before generic "engineer" / "data")
    (["software engineer", "software developer", "swe ", "backend", "frontend",
      "full stack", "mobile engineer", "platform engineer intern",
      "fullstack", "full-stack"], "software_engineering"),
    # Data / ML
    (["data scientist", "data analyst", "data engineer", "machine learning",
      "ml engineer", "analytics engineer", "data intern", "ai intern",
      "nlp ", "computer vision", "business intelligence", "bi analyst",
      "bi developer"], "data_ml"),
    # Product
    (["product manager", "product analyst", "product management",
      "product intern", "product owner"], "product"),
    # Infrastructure / devops
    (["devops", "infrastructure engineer", "sre ", "cloud engineer",
      "platform engineer", "site reliability"], "infrastructure"),
    # Design / UX
    (["ux designer", "product designer", "ui designer", "design intern",
      "ux intern", "user experience", "graphic designer", "ux researcher"], "design"),
    # Law
    (["training contract", "trainee solicitor", "trainee lawyer",
      "paralegal", "solicitor intern", "legal intern", "law intern",
      "vacation scheme", "legal vacation"], "law_corporate"),
    # Consulting / strategy
    (["consultant", "consulting intern", "strategy intern", "management consulting",
      "strategy analyst", "strategy associate", "business analyst",
      "graduate scheme consulting", "advisory analyst"], "consulting"),
    # Marketing (broad — catches executive, manager, coordinator, specialist variants)
    (["marketing", "brand manager", "brand analyst", "brand intern",
      "digital marketing", "growth intern", "growth marketing",
      "marketing associate", "comms intern", "pr intern", "pr manager",
      "social media", "content marketing", "content manager"], "marketing"),
    # Generic engineer catch-all
    (["engineer", "engineering intern", "engineering placement"], "software_engineering"),
    # Generic "investments" / "finance" catch-all
    (["investment intern", "investment analyst", "investments intern",
      "finance intern", "financial analyst", "financial intern"], "investment_banking"),
    # Technology / IT catch-all (before generic fallback)
    (["information technology", "it intern", " it analyst", "technology analyst",
      "technology intern", "technology programme", "technology summer"], "software_engineering"),
]


# ── Lead pre-fetch: university short name → full official name ────────────────
# Used when building Serper queries so Google matches the full name in profiles.

UNI_FULL_NAMES = {
    # UK
    "ucl":       "University College London",
    "lse":       "London School of Economics",
    "imperial":  "Imperial College London",
    "king's":    "King's College London",
    "kcl":       "King's College London",
    "oxford":    "University of Oxford",
    "cambridge": "University of Cambridge",
    "edinburgh": "University of Edinburgh",
    "manchester": "University of Manchester",
    "bristol":   "University of Bristol",
    "warwick":   "University of Warwick",
    "durham":    "Durham University",
    "exeter":    "University of Exeter",
    "bath":      "University of Bath",
    "glasgow":   "University of Glasgow",
    "sheffield": "University of Sheffield",
    "southampton": "University of Southampton",
    "nottingham": "University of Nottingham",
    "leeds":     "University of Leeds",
    "liverpool": "University of Liverpool",
    "birmingham": "University of Birmingham",
    "newcastle": "Newcastle University",
    "st andrews": "University of St Andrews",
    "cardiff":   "Cardiff University",
    "york":      "University of York",
    "lancaster": "Lancaster University",
    "leicester": "University of Leicester",
    "reading":   "University of Reading",
    "surrey":    "University of Surrey",
    "sussex":    "University of Sussex",
    "qmul":      "Queen Mary University of London",
    "qub":       "Queen's University Belfast",
    "loughborough": "Loughborough University",
    "strathclyde": "University of Strathclyde",
    "heriot-watt": "Heriot-Watt University",
    "soas":      "SOAS University of London",
    # US
    "harvard":   "Harvard University",
    "yale":      "Yale University",
    "princeton": "Princeton University",
    "stanford":  "Stanford University",
    "columbia":  "Columbia University",
    "upenn":     "University of Pennsylvania",
    "wharton":   "University of Pennsylvania",
    "mit":       "Massachusetts Institute of Technology",
    "berkeley":  "UC Berkeley",
    "nyu":       "New York University",
    "dartmouth": "Dartmouth College",
    "brown":     "Brown University",
    "cornell":   "Cornell University",
    "uchicago":  "University of Chicago",
    "northwestern": "Northwestern University",
    "duke":      "Duke University",
    "jhu":       "Johns Hopkins University",
    "ucla":      "University of California Los Angeles",
    "umich":     "University of Michigan",
    "georgetown": "Georgetown University",
    "cmu":       "Carnegie Mellon University",
}

# ── Russell Group universities (used for multi-uni lead scraping) ─────────────
RUSSELL_GROUP_UNIS = [
    "University of Oxford",
    "University of Cambridge",
    "London School of Economics and Political Science",
    "Imperial College London",
    "University College London",
    "University of Edinburgh",
    "University of Manchester",
    "King's College London",
    "University of Bristol",
    "University of Warwick",
    "University of Leeds",
    "University of Nottingham",
    "University of Birmingham",
    "University of Glasgow",
    "University of Sheffield",
    "Durham University",
    "University of Southampton",
    "University of Exeter",
    "Cardiff University",
    "Queen's University Belfast",
    "University of Liverpool",
    "Newcastle University",
    "University of York",
    "Queen Mary University of London",
]

# ── Lead pre-fetch: department → search keywords map ────────────────────────

DEPT_MAP = {
    "investment_banking": ["investment banking", "M&A", "analyst", "associate", "vice president"],
    "sales_trading":      ["sales trading", "trader", "markets", "fixed income", "FX", "derivatives",
                           "analyst", "associate", "vice president"],
    "asset_management":   ["asset management", "portfolio manager", "analyst", "associate"],
    "equity_research":    ["equity research", "research analyst", "analyst", "associate"],
    "risk":               ["risk", "risk analyst", "risk manager", "analyst", "associate"],
    "quant":              ["quantitative analyst", "quant", "quantitative researcher", "structurer"],
    "software_engineering": ["software engineer", "engineer", "developer", "swe"],
    "product":            ["product manager", "product analyst", "PM"],
    "data_ml":            ["data scientist", "machine learning engineer", "data analyst", "ML engineer",
                           "analytics engineer", "AI researcher"],
    "infrastructure":     ["infrastructure engineer", "devops", "platform engineer", "SRE",
                           "cloud engineer", "site reliability"],
    "design":             ["product designer", "UX designer", "designer", "UI designer"],
    "consulting":         ["consultant", "strategy", "management consulting", "business analyst",
                           "advisory", "associate consultant"],
    "marketing":          ["marketing", "brand", "growth", "communications", "PR", "digital marketing"],
    "law_corporate":      ["trainee", "associate", "partner", "solicitor", "M&A"],
    "law_finance":        ["trainee", "associate", "partner", "solicitor", "finance"],
    "law_disputes":       ["trainee", "associate", "partner", "solicitor", "litigation"],
    "law_tech":           ["trainee", "associate", "solicitor", "technology", "IP"],
    "healthcare":         ["life sciences", "clinical research", "pharmaceutical", "healthcare analyst",
                           "biotech", "medical devices", "health economics"],
    "general":            ["analyst", "associate", "intern"],
}

# ── Title → specific LinkedIn search keyword ─────────────────────────────────
# Checked against job title (lowercase) before falling back to DEPT_MAP[dept_tag][0].
# First match wins. Keeps searches specific so LinkedIn results are relevant.
TITLE_SEARCH_KEYWORD_MAP: list[tuple[list[str], str]] = [
    # ── Investment Banking sub-roles ──────────────────────────────────────────
    (["m&a", "mergers and acquisitions", "mergers &"],      "M&A analyst"),
    (["leveraged finance"],                                  "leveraged finance analyst"),
    (["dcm", "debt capital markets"],                        "DCM analyst"),
    (["ecm", "equity capital markets"],                      "ECM analyst"),
    (["restructuring"],                                      "restructuring analyst"),
    (["capital markets"],                                    "capital markets analyst"),
    (["corporate finance"],                                  "corporate finance analyst"),
    # ── Quant sub-roles ───────────────────────────────────────────────────────
    (["quantitative researcher", "quant research"],          "quantitative researcher"),
    (["quantitative trader", "quant trader"],                "quantitative trader"),
    (["structur"],                                           "structurer"),
    # ── Sales & Trading sub-roles ─────────────────────────────────────────────
    (["fixed income"],                                       "fixed income analyst"),
    (["fx trading", "fx trader", "foreign exchange"],        "FX trader"),
    (["derivatives"],                                        "derivatives analyst"),
    (["equity sales"],                                       "equity sales"),
    # ── Data sub-roles ────────────────────────────────────────────────────────
    (["data engineer"],                                      "data engineer"),
    (["business intelligence", "bi analyst", "bi developer"], "business intelligence analyst"),
    (["machine learning", "ml engineer"],                    "machine learning engineer"),
    (["analytics engineer"],                                 "analytics engineer"),
    (["data analyst"],                                       "data analyst"),
    (["data scientist"],                                     "data scientist"),
    (["ai researcher", "ai engineer", "ai intern"],          "AI engineer"),
    # ── Software Engineering sub-roles ───────────────────────────────────────
    (["backend", "back-end", "back end"],                    "backend engineer"),
    (["frontend", "front-end", "front end"],                 "frontend engineer"),
    (["full stack", "fullstack", "full-stack"],              "full stack engineer"),
    (["mobile engineer", "mobile developer", "ios ", "android "], "mobile engineer"),
    (["devops", "site reliability", "sre "],                 "DevOps engineer"),
    (["platform engineer", "infrastructure engineer"],       "platform engineer"),
    # ── Product sub-roles ─────────────────────────────────────────────────────
    (["product manager", "product management"],              "product manager"),
    (["product analyst"],                                    "product analyst"),
    # ── Design sub-roles ──────────────────────────────────────────────────────
    (["ux researcher"],                                      "UX researcher"),
    (["ux designer", "user experience designer"],            "UX designer"),
    (["ui designer", "user interface designer"],             "UI designer"),
    (["product designer"],                                   "product designer"),
    (["graphic designer"],                                   "graphic designer"),
    # ── Consulting sub-roles ──────────────────────────────────────────────────
    (["healthcare consultant", "life sciences consultant"],  "healthcare consultant"),
    (["strategy analyst", "strategy associate"],             "strategy analyst"),
    (["business analyst"],                                   "business analyst"),
    (["advisory analyst", "economic analyst"],               "economic analyst"),
    (["management consultant", "management consulting"],     "management consultant"),
    (["associate consultant"],                               "associate consultant"),
    # ── Marketing sub-roles ───────────────────────────────────────────────────
    (["digital marketing"],                                  "digital marketing manager"),
    (["brand manager", "brand analyst"],                     "brand manager"),
    (["growth marketing", "growth manager"],                 "growth manager"),
    (["content marketing", "content manager"],               "content marketer"),
    (["social media"],                                       "social media manager"),
    (["marketing analyst"],                                  "marketing analyst"),
    (["pr ", "public relations", "communications"],          "communications manager"),
    # ── Law sub-roles ─────────────────────────────────────────────────────────
    (["training contract", "trainee solicitor"],             "trainee solicitor"),
    (["paralegal"],                                          "paralegal"),
    (["vacation scheme"],                                    "trainee solicitor"),
    # ── Healthcare / Life Sciences ────────────────────────────────────────────
    (["clinical research associate", "cra "],                "clinical research associate"),
    (["clinical data", "clinical data analyst"],             "clinical data analyst"),
    (["health economics", "health economist"],               "health economist"),
    (["medical devices", "medical device"],                  "medical devices"),
    (["life sciences", "life science"],                      "life sciences"),
    (["pharmaceutical", "pharma analyst"],                   "pharmaceutical analyst"),
    (["biotech", "biotechnology"],                           "biotech analyst"),
    (["healthcare analyst"],                                 "healthcare analyst"),
]

# Maps Trackr industry → relevant DEPT_MAP keys
INDUSTRY_DEPT_MAP = {
    "Finance":            ["investment_banking", "sales_trading", "asset_management",
                           "equity_research", "risk", "quant"],
    "Investment Banking": ["investment_banking", "sales_trading", "risk", "quant"],
    "Software Engineering": ["software_engineering", "infrastructure", "data_ml"],
    "Technology":         ["product", "data_ml", "infrastructure"],
    "Data & Analytics":   ["data_ml", "software_engineering"],
    "Law":                ["law_corporate", "law_finance", "law_disputes", "law_tech"],
    "Consulting":         ["consulting", "investment_banking", "data_ml"],
    "Strategy":           ["consulting", "investment_banking"],
    "Marketing":          ["marketing", "product"],
    "Product Management": ["product", "software_engineering", "data_ml"],
    "Healthcare":         ["healthcare"],
}

# Fallback city per region if job has no location field
REGION_LOCATION_FALLBACK = {"UK": "London", "US": "New York", "EU": "Paris"}

# ── Company email formats ────────────────────────────────────────────────────
# Format codes: "FL" = firstname.lastname  "fL" = firstinitiallastname
#               "f.L" = firstinitial.lastname  "F_L" = firstname_lastname
#               "F"  = firstname only
# Keys are lowercase company names as they appear in the jobs/leads tables.
COMPANY_EMAIL_FORMATS: dict[str, tuple[str, str]] = {
    # ── Investment Banks ──────────────────────────────────────────────────────
    "goldman sachs":                ("FL",  "gs.com"),
    "morgan stanley":               ("FL",  "ms.com"),
    "jpmorgan":                     ("FL",  "jpmorgan.com"),
    "j.p. morgan":                  ("FL",  "jpmorgan.com"),
    "jp morgan":                    ("FL",  "jpmorgan.com"),
    "barclays":                     ("FL",  "barclays.com"),
    "barclays capital":             ("FL",  "barclays.com"),
    "deutsche bank":                ("FL",  "db.com"),
    "hsbc":                         ("FL",  "hsbc.com"),
    "citi":                         ("FL",  "citi.com"),
    "citigroup":                    ("FL",  "citi.com"),
    "citibank":                     ("FL",  "citi.com"),
    "ubs":                          ("FL",  "ubs.com"),
    "credit suisse":                ("FL",  "credit-suisse.com"),
    "bank of america":              ("FL",  "bofa.com"),
    "wells fargo":                  ("FL",  "wellsfargo.com"),
    "nomura":                       ("FL",  "nomura.com"),
    "nomura securities":            ("FL",  "nomura.com"),
    "jefferies":                    ("FL",  "jefferies.com"),
    "lazard":                       ("FL",  "lazard.com"),
    "rothschild":                   ("FL",  "rothschildandco.com"),
    "n.m. rothschild":              ("FL",  "rothschildandco.com"),
    "macquarie":                    ("FL",  "macquarie.com"),
    "rbc":                          ("FL",  "rbc.com"),
    "rbc capital markets":          ("FL",  "rbc.com"),
    "td securities":                ("FL",  "td.com"),
    "societe generale":             ("FL",  "sgcib.com"),
    "bnp paribas":                  ("FL",  "bnpparibas.com"),
    "natixis":                      ("FL",  "natixis.com"),
    "mizuho":                       ("FL",  "mizuho-sc.com"),
    "mufg":                         ("FL",  "mufg.jp"),
    "stifel":                       ("FL",  "stifel.com"),
    "piper sandler":                ("FL",  "pipersandler.com"),
    "canaccord genuity":            ("FL",  "canaccordgenuity.com"),
    "houlihan lokey":               ("FL",  "hl.com"),
    "evercore":                     ("FL",  "evercore.com"),
    "moelis":                       ("FL",  "moelis.com"),
    "centerview partners":          ("FL",  "centerviewpartners.com"),
    "perella weinberg":             ("FL",  "pwpartners.com"),
    "gleacher":                     ("FL",  "gleacher.com"),
    "abn amro":                     ("FL",  "abnamro.com"),
    "ing":                          ("FL",  "ing.com"),
    "commerzbank":                  ("FL",  "commerzbank.com"),
    "lloyds":                       ("FL",  "lloydsbanking.com"),
    "lloyds banking group":         ("FL",  "lloydsbanking.com"),
    "natwest":                      ("FL",  "natwest.com"),
    "santander":                    ("FL",  "santander.com"),
    "standard chartered":           ("FL",  "sc.com"),
    "raymond james":                ("FL",  "raymondjames.com"),
    "william blair":                ("FL",  "williamblair.com"),
    "baird":                        ("FL",  "rwbaird.com"),
    "cowen":                        ("FL",  "cowen.com"),
    # ── Asset Management ─────────────────────────────────────────────────────
    "blackrock":                    ("FL",  "blackrock.com"),
    "vanguard":                     ("FL",  "vanguard.com"),
    "fidelity":                     ("FL",  "fmr.com"),
    "fidelity investments":         ("FL",  "fmr.com"),
    "state street":                 ("FL",  "ssga.com"),
    "pimco":                        ("FL",  "pimco.com"),
    "bridgewater":                  ("FL",  "bwater.com"),
    "bridgewater associates":       ("FL",  "bwater.com"),
    "man group":                    ("FL",  "man.com"),
    "schroders":                    ("FL",  "schroders.com"),
    "abrdn":                        ("FL",  "abrdn.com"),
    "aberdeen":                     ("FL",  "abrdn.com"),
    "aberdeen group":               ("FL",  "abrdn.com"),
    "invesco":                      ("FL",  "invesco.com"),
    "wellington management":        ("FL",  "wellington.com"),
    "nuveen":                       ("FL",  "nuveen.com"),
    "franklin templeton":           ("FL",  "franklintempleton.com"),
    "t. rowe price":                ("FL",  "troweprice.com"),
    "t rowe price":                 ("FL",  "troweprice.com"),
    "alliancebernstein":            ("FL",  "alliancebernstein.com"),
    "alliance bernstein":           ("FL",  "alliancebernstein.com"),
    "allianz global investors":     ("FL",  "allianzgi.com"),
    "neuberger berman":             ("FL",  "nb.com"),
    "columbia threadneedle":        ("FL",  "columbiathreadneedle.com"),
    "aegon":                        ("FL",  "aegon.com"),
    "aegon asset management":       ("FL",  "aegon.com"),
    "aviva":                        ("FL",  "aviva.com"),
    "aviva investors":              ("FL",  "avivainvestors.com"),
    "legal & general":              ("FL",  "lgim.com"),
    "legal and general":            ("FL",  "lgim.com"),
    "m&g":                          ("FL",  "mandg.com"),
    "m&g investments":              ("FL",  "mandg.com"),
    "ubs asset management":         ("FL",  "ubs.com"),
    "pictet":                       ("FL",  "pictet.com"),
    "lombard odier":                ("FL",  "lombardodier.com"),
    "amundi":                       ("FL",  "amundi.com"),
    "axa investment managers":      ("FL",  "axa-im.com"),
    "axa im":                       ("FL",  "axa-im.com"),
    "baillie gifford":              ("FL",  "bailliegifford.com"),
    "liontrust":                    ("FL",  "liontrust.co.uk"),
    "rathbones":                    ("FL",  "rathbones.com"),
    "royal london":                 ("FL",  "royallondon.com"),
    "jupiter":                      ("FL",  "jupiteram.com"),
    "jupiter asset management":     ("FL",  "jupiteram.com"),
    "janus henderson":              ("FL",  "janushenderson.com"),
    "pgim":                         ("FL",  "pgim.com"),
    "ninepoint partners":           ("FL",  "ninepoint.com"),
    "charlesbank":                  ("FL",  "charlesbank.com"),
    "7im":                          ("FL",  "7im.co.uk"),
    "addepar":                      ("FL",  "addepar.com"),
    "aqr capital management":       ("FL",  "aqr.com"),
    "aqr":                          ("FL",  "aqr.com"),
    # ── Hedge Funds ──────────────────────────────────────────────────────────
    "citadel":                      ("FL",  "citadel.com"),
    "citadel securities":           ("FL",  "citadelsecurities.com"),
    "two sigma":                    ("FL",  "twosigma.com"),
    "de shaw":                      ("FL",  "deshaw.com"),
    "d.e. shaw":                    ("FL",  "deshaw.com"),
    "renaissance technologies":     ("FL",  "rentec.com"),
    "point72":                      ("FL",  "point72.com"),
    "millennium":                   ("FL",  "mlp.com"),
    "millennium management":        ("FL",  "mlp.com"),
    "winton":                       ("FL",  "winton.com"),
    "brevan howard":                ("FL",  "brevanhoward.com"),
    "marshall wace":                ("FL",  "mwam.com"),
    "tudor":                        ("FL",  "tudor.com"),
    "tudor investment":             ("FL",  "tudor.com"),
    "och-ziff":                     ("FL",  "ozm.com"),
    "glenview capital":             ("FL",  "glenviewcapital.com"),
    "balyasny":                     ("FL",  "bamfunds.com"),
    "third point":                  ("FL",  "thirdpoint.com"),
    "pershing square":              ("FL",  "pershingsquare.com"),
    "akuna capital":                ("FL",  "akunacapital.com"),
    "aquatic capital management":   ("FL",  "aquaticcapital.com"),
    "jane street":                  ("FL",  "janestreet.com"),
    "virtu financial":              ("FL",  "virtu.com"),
    "jump trading":                 ("FL",  "jumptrading.com"),
    # ── Private Equity ───────────────────────────────────────────────────────
    "kkr":                          ("FL",  "kkr.com"),
    "blackstone":                   ("FL",  "blackstone.com"),
    "apollo":                       ("FL",  "apollo.com"),
    "apollo global management":     ("FL",  "apollo.com"),
    "carlyle":                      ("FL",  "carlyle.com"),
    "the carlyle group":            ("FL",  "carlyle.com"),
    "warburg pincus":               ("FL",  "warburgpincus.com"),
    "cvc":                          ("FL",  "cvc.com"),
    "cvc capital":                  ("FL",  "cvc.com"),
    "cvc capital partners":         ("FL",  "cvc.com"),
    "bc partners":                  ("FL",  "bcpartners.com"),
    "apax":                         ("FL",  "apax.com"),
    "apax partners":                ("FL",  "apax.com"),
    "ardian":                       ("FL",  "ardian.com"),
    "permira":                      ("FL",  "permira.com"),
    "3i":                           ("FL",  "3i.com"),
    "3i group":                     ("FL",  "3i.com"),
    "advent international":         ("FL",  "adventinternational.com"),
    "bain capital":                 ("FL",  "baincapital.com"),
    "tpg":                          ("FL",  "tpg.com"),
    "ares management":              ("FL",  "aresmgmt.com"),
    "ares":                         ("FL",  "aresmgmt.com"),
    "hg":                           ("FL",  "hgcapital.com"),
    "hg capital":                   ("FL",  "hgcapital.com"),
    "bridgepoint":                  ("FL",  "bridgepoint.eu"),
    "cinven":                       ("FL",  "cinven.com"),
    "pantheon":                     ("FL",  "pantheon.com"),
    "icg":                          ("FL",  "icgam.com"),
    "intermediate capital":         ("FL",  "icgam.com"),
    "lion capital":                 ("FL",  "lioncapital.com"),
    "vitruvian partners":           ("FL",  "vitruvianpartners.com"),
    "harvest partners":             ("FL",  "harvestpartners.com"),
    "vista equity":                 ("FL",  "vistaequitypartners.com"),
    "vista equity partners":        ("FL",  "vistaequitypartners.com"),
    "alpine investors":             ("FL",  "alpineinvestors.com"),
    "battery":                      ("FL",  "battery.com"),
    "battery ventures":             ("FL",  "battery.com"),
    "revaia":                       ("FL",  "revaia.com"),
    "intriva":                      ("FL",  "intrivacapital.com"),
    "intriva capital":              ("FL",  "intrivacapital.com"),
    "equiteq":                      ("FL",  "equiteq.com"),
    "la caisse":                    ("FL",  "cdpq.com"),
    "uvimco":                       ("FL",  "uvimco.com"),
    # ── Strategy Consulting ──────────────────────────────────────────────────
    "mckinsey":                     ("F_L", "mckinsey.com"),
    "mckinsey & company":           ("F_L", "mckinsey.com"),
    "bcg":                          ("FL",  "bcg.com"),
    "boston consulting group":      ("FL",  "bcg.com"),
    "the boston consulting group":  ("FL",  "bcg.com"),
    "bain":                         ("FL",  "bain.com"),
    "bain & company":               ("FL",  "bain.com"),
    "oliver wyman":                 ("FL",  "oliverwyman.com"),
    "lek":                          ("FL",  "lek.com"),
    "lek consulting":               ("FL",  "lek.com"),
    "roland berger":                ("FL",  "rolandberger.com"),
    "at kearney":                   ("FL",  "kearney.com"),
    "a.t. kearney":                 ("FL",  "kearney.com"),
    "kearney":                      ("FL",  "kearney.com"),
    "strategy&":                    ("FL",  "strategyand.us.pwc.com"),
    "alixpartners":                 ("FL",  "alixpartners.com"),
    "alvarez & marsal":             ("FL",  "alvarezandmarsal.com"),
    "fp&a":                         ("FL",  "fpanda.com"),
    "pa consulting":                ("FL",  "paconsulting.com"),
    "analysys mason":               ("FL",  "analysysmason.com"),
    # ── Big 4 / Accounting ───────────────────────────────────────────────────
    "deloitte":                     ("FL",  "deloitte.co.uk"),
    "pwc":                          ("FL",  "pwc.com"),
    "pricewaterhousecoopers":       ("FL",  "pwc.com"),
    "ey":                           ("FL",  "ey.com"),
    "ernst & young":                ("FL",  "ey.com"),
    "kpmg":                         ("FL",  "kpmg.co.uk"),
    "accenture":                    ("FL",  "accenture.com"),
    "bdo":                          ("FL",  "bdo.co.uk"),
    "grant thornton":               ("FL",  "grantthornton.co.uk"),
    "rsm":                          ("FL",  "rsmuk.com"),
    "mazars":                       ("FL",  "mazars.com"),
    # ── Law Firms ────────────────────────────────────────────────────────────
    "clifford chance":              ("FL",  "cliffordchance.com"),
    "linklaters":                   ("FL",  "linklaters.com"),
    "allen & overy":                ("FL",  "allenovery.com"),
    "a&o shearman":                 ("FL",  "aoshearman.com"),
    "freshfields":                  ("FL",  "freshfields.com"),
    "freshfields bruckhaus deringer": ("FL","freshfields.com"),
    "slaughter and may":            ("FL",  "slaughterandmay.com"),
    "herbert smith freehills":      ("FL",  "hsf.com"),
    "ashurst":                      ("FL",  "ashurst.com"),
    "hogan lovells":                ("FL",  "hoganlovells.com"),
    "baker mckenzie":               ("FL",  "bakermckenzie.com"),
    "norton rose fulbright":        ("FL",  "nortonrosefulbright.com"),
    "dla piper":                    ("FL",  "dlapiper.com"),
    "simmons & simmons":            ("FL",  "simmons-simmons.com"),
    "travers smith":                ("FL",  "traverssmith.com"),
    "walker morris":                ("FL",  "walkermorris.co.uk"),
    "addleshaw goddard":            ("FL",  "addleshawgoddard.com"),
    "squire patton boggs":          ("FL",  "squirepb.com"),
    "eversheds sutherland":         ("FL",  "eversheds-sutherland.com"),
    "cms":                          ("FL",  "cms-cmno.com"),
    "bird & bird":                  ("FL",  "twobirds.com"),
    "pinsent masons":               ("FL",  "pinsentmasons.com"),
    "macfarlanes":                  ("FL",  "macfarlanes.com"),
    "sidley austin":                ("FL",  "sidley.com"),
    "kirkland & ellis":             ("FL",  "kirkland.com"),
    "latham & watkins":             ("FL",  "lw.com"),
    "skadden":                      ("FL",  "skadden.com"),
    "weil gotshal":                 ("FL",  "weil.com"),
    "white & case":                 ("FL",  "whitecase.com"),
    "sullivan & cromwell":          ("FL",  "sullcrom.com"),
    "paul weiss":                   ("FL",  "paulweiss.com"),
    "cleary gottlieb":              ("FL",  "cgsh.com"),
    "shearman & sterling":          ("FL",  "shearman.com"),
    "milbank":                      ("FL",  "milbank.com"),
    "debevoise":                    ("FL",  "debevoise.com"),
    "ropes & gray":                 ("FL",  "ropesgray.com"),
    "orrick":                       ("FL",  "orrick.com"),
    # ── Tech ─────────────────────────────────────────────────────────────────
    "amazon":                       ("FL",  "amazon.com"),
    "aws":                          ("FL",  "amazon.com"),
    "google":                       ("FL",  "google.com"),
    "alphabet":                     ("FL",  "google.com"),
    "microsoft":                    ("FL",  "microsoft.com"),
    "apple":                        ("FL",  "apple.com"),
    "meta":                         ("FL",  "meta.com"),
    "netflix":                      ("FL",  "netflix.com"),
    "salesforce":                   ("FL",  "salesforce.com"),
    "adobe":                        ("FL",  "adobe.com"),
    "palantir":                     ("FL",  "palantir.com"),
    "stripe":                       ("FL",  "stripe.com"),
    "airbnb":                       ("FL",  "airbnb.com"),
    "uber":                         ("FL",  "uber.com"),
    "spotify":                      ("FL",  "spotify.com"),
    "monzo":                        ("FL",  "monzo.com"),
    "revolut":                      ("FL",  "revolut.com"),
    "wise":                         ("FL",  "wise.com"),
    "transferwise":                 ("FL",  "wise.com"),
    "arm":                          ("FL",  "arm.com"),
    "amd":                          ("FL",  "amd.com"),
    "intel":                        ("FL",  "intel.com"),
    "nvidia":                       ("FL",  "nvidia.com"),
    "ibm":                          ("FL",  "ibm.com"),
    "oracle":                       ("FL",  "oracle.com"),
    "sap":                          ("FL",  "sap.com"),
    "servicenow":                   ("FL",  "servicenow.com"),
    "workday":                      ("FL",  "workday.com"),
    "snowflake":                    ("FL",  "snowflake.com"),
    "databricks":                   ("FL",  "databricks.com"),
    "datadog":                      ("FL",  "datadoghq.com"),
    "twilio":                       ("FL",  "twilio.com"),
    "zendesk":                      ("FL",  "zendesk.com"),
    "hubspot":                      ("FL",  "hubspot.com"),
    "shopify":                      ("FL",  "shopify.com"),
    "square":                       ("FL",  "squareup.com"),
    "block":                        ("FL",  "squareup.com"),
    "coinbase":                     ("FL",  "coinbase.com"),
    "roku":                         ("FL",  "roku.com"),
    # ── Other Financial Services ─────────────────────────────────────────────
    "aig":                          ("FL",  "aig.com"),
    "aon":                          ("FL",  "aon.com"),
    "marsh":                        ("FL",  "marsh.com"),
    "willis towers watson":         ("FL",  "willistowerswatson.com"),
    "wtw":                          ("FL",  "willistowerswatson.com"),
    "american express":             ("FL",  "aexp.com"),
    "visa":                         ("FL",  "visa.com"),
    "mastercard":                   ("FL",  "mastercard.com"),
    "charles schwab":               ("FL",  "schwab.com"),
    "interactive brokers":          ("FL",  "ibkr.com"),
    "bloomberg":                    ("FL",  "bloomberg.net"),
    "refinitiv":                    ("FL",  "refinitiv.com"),
    "msci":                         ("FL",  "msci.com"),
    "factset":                      ("FL",  "factset.com"),
    "morningstar":                  ("FL",  "morningstar.com"),
    "aj bell":                      ("FL",  "ajbell.co.uk"),
    "hargreaves lansdown":          ("FL",  "hl.co.uk"),
    "st. james's place":            ("FL",  "sjp.co.uk"),
    "arbuthnot latham":             ("FL",  "arbuthnotlatham.co.uk"),
    "rathbones":                    ("FL",  "rathbones.com"),
    "investec":                     ("FL",  "investec.com"),
    "quilter":                      ("FL",  "quilter.com"),
    "cazenove":                     ("FL",  "cazenove.com"),
    "numis":                        ("FL",  "numis.com"),
    "berenberg":                    ("FL",  "berenberg.com"),
    "peel hunt":                    ("FL",  "peelhunt.com"),
    "shore capital":                ("FL",  "shorecap.co.uk"),
    # ── Additional firms ─────────────────────────────────────────────────────
    "17capital":                    ("FL",  "17capital.com"),
    "aab group":                    ("FL",  "aab.co.uk"),
    "abdiel capital":               ("FL",  "abdielcapital.com"),
    "abrahams dresden":             ("FL",  "abrahams-dresden.co.uk"),
    "accelercomm":                  ("FL",  "accelercomm.com"),
    "access capital partners":      ("FL",  "access-capital.com"),
    "accuracy":                     ("FL",  "accuracy.com"),
    "activumsg":                    ("FL",  "activumsg.com"),
    "acuity law":                   ("FL",  "acuitylaw.com"),
    "adams street partners":        ("FL",  "adamsstreetpartners.com"),
    "aew capital management":       ("FL",  "aew.com"),
    "aew":                          ("FL",  "aew.com"),
    "affinius capital":             ("FL",  "affiniuscapital.com"),
    "afry capital":                 ("FL",  "afry.com"),
    "agc partners":                 ("FL",  "agcpartners.com"),
    "ageas":                        ("FL",  "ageas.com"),
    "agentis capital":              ("FL",  "agentiscapital.com"),
    "agwest farm credit":           ("FL",  "agwestfc.com"),
    "akereos capital":              ("FL",  "akereoscapital.com"),
    "alantra":                      ("FL",  "alantra.com"),
    "alexa capital":                ("FL",  "alexacapital.co.uk"),
    "allia c&c":                    ("FL",  "alliacc.com"),
    "allianz insurance":            ("FL",  "allianz.co.uk"),
    "allied world":                 ("FL",  "awac.com"),
    "allstate":                     ("FL",  "allstate.com"),
    "alpha fmc":                    ("FL",  "alphafmc.com"),
    "alphasights":                  ("FL",  "alphasights.com"),
    "altana wealth":                ("FL",  "altanawealth.com"),
    "altman solon":                 ("FL",  "altmansolon.com"),
    "altus group":                  ("FL",  "altusgroup.com"),
    "alvine capital":               ("FL",  "alvinecapital.com"),
    "anesi advisors":               ("FL",  "anesi.com"),
    "ankura":                       ("FL",  "ankura.com"),
    "antin infrastructure partners": ("FL", "antin-ip.com"),
    "apg capital markets":          ("FL",  "apg.nl"),
    "apogem capital":               ("FL",  "apogemcapital.com"),
    "aq technology partners":       ("FL",  "aqtp.co.uk"),
    "arcadis":                      ("FL",  "arcadis.com"),
    "arch insurance international": ("FL",  "archinsurance.com"),
    "arctic lake":                  ("FL",  "arcticlake.co.uk"),
    "ardea partners":               ("FL",  "ardeapartners.com"),
    "arena investors":              ("FL",  "arenainvestors.com"),
    "aries global":                 ("FL",  "ariesglobal.com"),
    "armanino":                     ("FL",  "armaninollp.com"),
    "arma partners":                ("FL",  "armapartners.com"),
    "arnold & porter":              ("FL",  "arnoldporter.com"),
    "arthur d. little":             ("FL",  "adlittle.com"),
    "arthur d little":              ("FL",  "adlittle.com"),
    "ashfords":                     ("FL",  "ashfords.co.uk"),
    "aspect capital":               ("FL",  "aspectcapital.com"),
    "astorg":                       ("FL",  "astorg.com"),
    "astrazeneca":                  ("FL",  "astrazeneca.com"),
    "audax group":                  ("FL",  "audaxgroup.com"),
    "australiansuper":              ("FL",  "australiansuper.com"),
    "autodesk":                     ("FL",  "autodesk.com"),
    "aveva":                        ("FL",  "aveva.com"),
    "axa":                          ("FL",  "axa.com"),
    "axiom alternative investments": ("FL", "axiom-ai.com"),
    "azets":                        ("FL",  "azets.co.uk"),
    "b2c2":                         ("FL",  "b2c2.com"),
    "bae systems":                  ("FL",  "baesystems.com"),
    "baker hughes":                 ("FL",  "bakerhughes.com"),
    "baker tilly":                  ("FL",  "bakertilly.com"),
    "balyasny asset management":    ("FL",  "bamfunds.com"),
    "bank of china":                ("FL",  "bankofchina.com"),
    "bank of england":              ("FL",  "bankofengland.co.uk"),
    "baringa":                      ("FL",  "baringa.com"),
    "barings":                      ("FL",  "barings.com"),
    "barnett waddingham":           ("FL",  "barnettwaddingham.co.uk"),
    "bastion trading":              ("FL",  "bastiontrading.com"),
    "bbva":                         ("FL",  "bbva.com"),
    "bda partners":                 ("FL",  "bdapartners.com"),
    "bdo global":                   ("FL",  "bdo.com"),
    "benefit street partners":      ("FL",  "benefitstreetpartners.com"),
    "berenberg":                    ("FL",  "berenberg.com"),
    "berkeley research group":      ("FL",  "thinkbrg.com"),
    "brg":                          ("FL",  "thinkbrg.com"),
    "bessemer venture partners":    ("FL",  "bvp.com"),
    "bevan brittan":                ("FL",  "bevanbrittan.com"),
    "bgc group":                    ("FL",  "bgcpartners.com"),
    "bgf":                          ("FL",  "bgf.co.uk"),
    "bird & bird":                  ("FL",  "twobirds.com"),
    "blackfin capital partners":    ("FL",  "blackfin.vc"),
    "blackfinch group":             ("FL",  "blackfinch.com"),
    "blue owl capital":             ("FL",  "blueowl.com"),
    "bluecrest capital management": ("FL",  "bluecrest.com"),
    "bluecrest":                    ("FL",  "bluecrest.com"),
    "bmll":                         ("FL",  "bmlltech.com"),
    "bmo capital markets":          ("FL",  "bmo.com"),
    "bny mellon":                   ("FL",  "bnymellon.com"),
    "bp":                           ("FL",  "bp.com"),
    "brabners":                     ("FL",  "brabners.com"),
    "bracebridge capital":          ("FL",  "bracebridgecapital.com"),
    "breega":                       ("FL",  "breega.com"),
    "bridgewater":                  ("FL",  "bwater.com"),
    "bristows":                     ("FL",  "bristows.com"),
    "british airways":              ("FL",  "ba.com"),
    "british business bank":        ("FL",  "british-business-bank.co.uk"),
    "british land":                 ("FL",  "britishland.com"),
    "brookfield":                   ("FL",  "brookfield.com"),
    "brown advisory":               ("FL",  "brownadvisory.com"),
    "browne jacobson":              ("FL",  "brownejacobson.com"),
    "brown shipley":                ("FL",  "brownshipley.com"),
    "bryan cave leighton paisner":  ("FL",  "bclplaw.com"),
    "bclp":                         ("FL",  "bclplaw.com"),
    "bt":                           ("FL",  "bt.com"),
    "btg pactual":                  ("FL",  "btgpactual.com"),
    "burford capital":              ("FL",  "burfordcapital.com"),
    "burges salmon":                ("FL",  "burges-salmon.com"),
    "cabot properties":             ("FL",  "cabotprop.com"),
    "caledonia investments":        ("FL",  "caledonia.com"),
    "cambridge associates":         ("FL",  "cambridgeassociates.com"),
    "campbell lutyens":             ("FL",  "campbelllutyens.com"),
    "canada life":                  ("FL",  "canadalife.co.uk"),
    "canary wharf group":           ("FL",  "canarywharf.com"),
    "cantor fitzgerald":            ("FL",  "cantor.com"),
    "capgemini":                    ("FL",  "capgemini.com"),
    "capital group":                ("FL",  "capitalgroup.com"),
    "capital one":                  ("FL",  "capitalone.com"),
    "capstone partners":            ("FL",  "capstonepartners.com"),
    "capula investment management": ("FL",  "capula.com"),
    "carlsquare":                   ("FL",  "carlsquare.com"),
    "cbre":                         ("FL",  "cbre.com"),
    "caxton associates":            ("FL",  "caxton.com"),
    "centerview partners":          ("FL",  "centerviewpartners.com"),
    "cerberus capital management":  ("FL",  "cerberuscapital.com"),
    "cfc":                          ("FL",  "cfc.com"),
    "charles river associates":     ("FL",  "crai.com"),
    "charles russell speechlys":    ("FL",  "crsblaw.com"),
    "chatham financial":            ("FL",  "chathamfinancial.com"),
    "checkout.com":                 ("FL",  "checkout.com"),
    "chicago trading company":      ("FL",  "chicagotrading.com"),
    "cibc":                         ("FL",  "cibc.com"),
    "cinven":                       ("FL",  "cinven.com"),
    "cisco":                        ("FL",  "cisco.com"),
    "citco":                        ("FL",  "citco.com"),
    "citizens financial group":     ("FL",  "citizensbank.com"),
    "clarksons":                    ("FL",  "clarksons.com"),
    "cliftonlarsonallen":           ("FL",  "claconnect.com"),
    "cla":                          ("FL",  "claconnect.com"),
    "cloudflare":                   ("FL",  "cloudflare.com"),
    "clyde & co":                   ("FL",  "clydeco.com"),
    "cme group":                    ("FL",  "cmegroup.com"),
    "cms":                          ("FL",  "cms-cmno.com"),
    "cohen & company":              ("FL",  "cohencompany.com"),
    "cohnreznick":                  ("FL",  "cohnreznick.com"),
    "colliers":                     ("FL",  "colliers.com"),
    "columbia threadneedle investments": ("FL", "columbiathreadneedle.com"),
    "compass lexecon":              ("FL",  "compasslexecon.com"),
    "cornerstone research":         ("FL",  "cornerstone.com"),
    "coutts":                       ("FL",  "coutts.com"),
    "creandum":                     ("FL",  "creandum.com"),
    "credit agricole":              ("FL",  "ca-cib.com"),
    "crédit agricole":              ("FL",  "ca-cib.com"),
    "cushman & wakefield":          ("FL",  "cushwake.com"),
    "cvc":                          ("FL",  "cvc.com"),
    "d.a. davidson":                ("FL",  "dadavidson.com"),
    "da vinci trading":             ("FL",  "davincitg.com"),
    "dc advisory":                  ("FL",  "dcadvisory.com"),
    "dechert":                      ("FL",  "dechert.com"),
    "deliveroo":                    ("FL",  "deliveroo.com"),
    "dentons":                      ("FL",  "dentons.com"),
    "d.e. shaw":                    ("FL",  "deshaw.com"),
    "digitalbridge":                ("FL",  "digitalbridge.com"),
    "dimensional fund advisors":    ("FL",  "dimensional.com"),
    "dimensional":                  ("FL",  "dimensional.com"),
    "dodge & cox":                  ("FL",  "dodgeandcox.com"),
    "dojo":                         ("FL",  "dojo.tech"),
    "dow jones":                    ("FL",  "dowjones.com"),
    "drw":                          ("FL",  "drwtrading.com"),
    "dws":                          ("FL",  "dws.com"),
    "ebay":                         ("FL",  "ebay.com"),
    "ebrd":                         ("FL",  "ebrd.com"),
    "edf trading":                  ("FL",  "edftrading.com"),
    "eqt":                          ("FL",  "eqtgroup.com"),
    "equinor":                      ("FL",  "equinor.com"),
    "equitix":                      ("FL",  "equitix.com"),
    "eurazeo":                      ("FL",  "eurazeo.com"),
    "eurostar":                     ("FL",  "eurostar.com"),
    "evelyn partners":              ("FL",  "evelynpartners.com"),
    "everest":                      ("FL",  "everestgrp.com"),
    "exoduspoint":                  ("FL",  "exoduspoint.com"),
    "expedia":                      ("FL",  "expedia.com"),
    "exxonmobil":                   ("FL",  "exxonmobil.com"),
    "ey-parthenon":                 ("FL",  "ey.com"),
    "factset":                      ("FL",  "factset.com"),
    "farrer & co":                  ("FL",  "farrer.co.uk"),
    "fasanara capital":             ("FL",  "fasanara.com"),
    "fenchurch advisory":           ("FL",  "fenchurchadvisory.com"),
    "fidelity international":       ("FL",  "fil.com"),
    "fieldfisher":                  ("FL",  "fieldfisher.com"),
    "financial conduct authority":  ("FL",  "fca.org.uk"),
    "fca":                          ("FL",  "fca.org.uk"),
    "financial times":              ("FL",  "ft.com"),
    "fisher investments":           ("FL",  "fi.com"),
    "fitch ratings":                ("FL",  "fitchratings.com"),
    "five arrows":                  ("FL",  "fivearrows.com"),
    "five rings":                   ("FL",  "fiverings.com"),
    "flow traders":                 ("FL",  "flowtraders.com"),
    "foot anstey":                  ("FL",  "footanstey.com"),
    "forsters":                     ("FL",  "forsters.co.uk"),
    "forvis mazars":                ("FL",  "forvismazars.com"),
    "franklin templeton":           ("FL",  "franklintempleton.com"),
    "fried frank":                  ("FL",  "friedfrank.com"),
    "frontier economics":           ("FL",  "frontier-economics.com"),
    "fti consulting":               ("FL",  "fticonsulting.com"),
    "general atlantic":             ("FL",  "generalatlantic.com"),
    "general electric":             ("FL",  "ge.com"),
    "gcm grosvenor":                ("FL",  "gcmlp.com"),
    "gibson dunn":                  ("FL",  "gibsondunn.com"),
    "gic":                          ("FL",  "gic.com.sg"),
    "gleacher shacklock":           ("FL",  "gleachershacklock.com"),
    "glg":                          ("FL",  "glg.com"),
    "global atlantic":              ("FL",  "globalatlantic.com"),
    "goldman sachs asset management": ("FL", "gs.com"),
    "goodwin":                      ("FL",  "goodwinlaw.com"),
    "goodwin procter":              ("FL",  "goodwinlaw.com"),
    "government economic service":  ("FL",  "hmtreasury.gov.uk"),
    "gsk":                          ("FL",  "gsk.com"),
    "gtcr":                         ("FL",  "gtcr.com"),
    "guggenheim partners":          ("FL",  "guggenheimpartners.com"),
    "guidehouse":                   ("FL",  "guidehouse.com"),
    "gunvor":                       ("FL",  "gunvorgroup.com"),
    "guy carpenter":                ("FL",  "guycarpenter.com"),
    "hamilton lane":                ("FL",  "hamiltonlane.com"),
    "hannam & partners":            ("FL",  "hannamandpartners.com"),
    "harbourvest":                  ("FL",  "harbourvest.com"),
    "harris williams":              ("FL",  "harriswilliams.com"),
    "hayfin capital management":    ("FL",  "hayfin.com"),
    "hayfin":                       ("FL",  "hayfin.com"),
    "helsing":                      ("FL",  "helsing.ai"),
    "hfw":                          ("FL",  "hfw.com"),
    "h.i.g. capital":               ("FL",  "higcapital.com"),
    "hig capital":                  ("FL",  "higcapital.com"),
    "hill dickinson":               ("FL",  "hilldickinson.com"),
    "hines":                        ("FL",  "hines.com"),
    "hiscox":                       ("FL",  "hiscox.com"),
    "houlihan lokey":               ("FL",  "hl.com"),
    "howden":                       ("FL",  "howdengroup.com"),
    "hp":                           ("FL",  "hp.com"),
    "hudson river trading":         ("FL",  "hudsonrivertrading.com"),
    "hrt":                          ("FL",  "hudsonrivertrading.com"),
    "hymans robertson":             ("FL",  "hymans.co.uk"),
    "ibm":                          ("FL",  "ibm.com"),
    "icbc standard bank":           ("FL",  "icbcstandard.com"),
    "ice":                          ("FL",  "ice.com"),
    "ik partners":                  ("FL",  "ikpartners.com"),
    "imc trading":                  ("FL",  "imc.com"),
    "impax asset management":       ("FL",  "impaxam.com"),
    "infosys":                      ("FL",  "infosys.com"),
    "infrared capital partners":    ("FL",  "ircp.com"),
    "ing":                          ("FL",  "ing.com"),
    "insight partners":             ("FL",  "insightpartners.com"),
    "interpath advisory":           ("FL",  "interpathadvisory.com"),
    "intesa sanpaolo":              ("FL",  "intesasanpaolo.com"),
    "inverto":                      ("FL",  "inverto.com"),
    "iqt":                          ("FL",  "iqt.org"),
    "irwin mitchell":               ("FL",  "irwinmitchell.com"),
    "isio":                         ("FL",  "isio.com"),
    "ithaca energy":                ("FL",  "ithacaenergy.com"),
    "iwoca":                        ("FL",  "iwoca.co.uk"),
    "jacobs":                       ("FL",  "jacobs.com"),
    "jane street":                  ("FL",  "janestreet.com"),
    "javelin global commodities":   ("FL",  "javelincommodities.com"),
    "jll":                          ("FL",  "jll.com"),
    "johnson & johnson":            ("FL",  "its.jnj.com"),
    "johnson lambert":              ("FL",  "johnsonlambert.com"),
    "johnston carmichael":          ("FL",  "jcca.co.uk"),
    "julius baer":                  ("FL",  "juliusbaer.com"),
    "jump trading":                 ("FL",  "jumptrading.com"),
    "kartesia":                     ("FL",  "kartesia.com"),
    "kennedys":                     ("FL",  "kennedyslaw.com"),
    "keybank":                      ("FL",  "keybank.com"),
    "king":                         ("FL",  "king.com"),
    "kirkland & ellis":             ("FL",  "kirkland.com"),
    "knight frank":                 ("FL",  "knightfrank.com"),
    "korn ferry":                   ("FL",  "kornferry.com"),
    "kroll":                        ("FL",  "kroll.com"),
    "la caisse":                    ("FL",  "cdpq.com"),
    "cdpq":                         ("FL",  "cdpq.com"),
    "lasalle":                      ("FL",  "lasalle.com"),
    "lazard asset management":      ("FL",  "lazard.com"),
    "lcp":                          ("FL",  "lcp.uk.com"),
    "lead edge capital":            ("FL",  "leadedgecapital.com"),
    "lendable":                     ("FL",  "lendable.co.uk"),
    "lenovo":                       ("FL",  "lenovo.com"),
    "lewis silkin":                 ("FL",  "lewissilkin.com"),
    "lgt":                          ("FL",  "lgt.com"),
    "lgt capital partners":         ("FL",  "lgtcp.com"),
    "lgt wealth management":        ("FL",  "lgtwm.com"),
    "liberty global":               ("FL",  "libertyglobal.com"),
    "lincoln international":        ("FL",  "lincolninternational.com"),
    "liontree":                     ("FL",  "liontree.com"),
    "liquidnet":                    ("FL",  "liquidnet.com"),
    "llr partners":                 ("FL",  "llrpartners.com"),
    "lmr partners":                 ("FL",  "lmrpartners.com"),
    "lockton":                      ("FL",  "lockton.com"),
    "london stock exchange group":  ("FL",  "lseg.com"),
    "lseg":                         ("FL",  "lseg.com"),
    "l'oreal":                      ("FL",  "loreal.com"),
    "lothian pension fund":         ("FL",  "lpf.org.uk"),
    "macquarie group":              ("FL",  "macquarie.com"),
    "mako trading":                 ("FL",  "makotrading.com"),
    "marathon capital":             ("FL",  "marathoncapital.com"),
    "marex":                        ("FL",  "marex.com"),
    "markel":                       ("FL",  "markel.com"),
    "marketaxess":                  ("FL",  "marketaxess.com"),
    "marsh mclennan":               ("FL",  "mmc.com"),
    "mayer brown":                  ("FL",  "mayerbrown.com"),
    "mcdermott will & emery":       ("FL",  "mwe.com"),
    "mcguirewoods":                 ("FL",  "mcguirewoods.com"),
    "mediobanca":                   ("FL",  "mediobanca.com"),
    "menzies":                      ("FL",  "menzies.co.uk"),
    "mercer":                       ("FL",  "mercer.com"),
    "merqube":                      ("FL",  "merqube.com"),
    "meta":                         ("FL",  "meta.com"),
    "mewburn ellis":                ("FL",  "mewburn.com"),
    "mfs":                          ("FL",  "mfs.com"),
    "michelmores":                  ("FL",  "michelmores.com"),
    "millennium management":        ("FL",  "mlp.com"),
    "mizuho":                       ("FL",  "mizuho-sc.com"),
    "moelis & co":                  ("FL",  "moelis.com"),
    "mongodb":                      ("FL",  "mongodb.com"),
    "moody's":                      ("FL",  "moodys.com"),
    "moore barlow":                 ("FL",  "moorebarlow.co.uk"),
    "morgan lewis":                 ("FL",  "morganlewis.com"),
    "motorola solutions":           ("FL",  "motorolasolutions.com"),
    "msci":                         ("FL",  "msci.com"),
    "mubadala capital":             ("FL",  "mubadala.ae"),
    "munich re":                    ("FL",  "munichre.com"),
    "mv credit":                    ("FL",  "mvcredit.com"),
    "nasdaq":                       ("FL",  "nasdaq.com"),
    "national audit office":        ("FL",  "nao.org.uk"),
    "national gas":                 ("FL",  "nationalgas.com"),
    "national highways":            ("FL",  "nationalhighways.co.uk"),
    "nationwide":                   ("FL",  "nationwide.co.uk"),
    "natwest markets":              ("FL",  "natwestmarkets.com"),
    "natwest":                      ("FL",  "natwest.com"),
    "nera":                         ("FL",  "nera.com"),
    "netflix":                      ("FL",  "netflix.com"),
    "network rail":                 ("FL",  "networkrail.co.uk"),
    "neuberger berman":             ("FL",  "nb.com"),
    "ninety one":                   ("FL",  "ninetyone.com"),
    "nomura securities":            ("FL",  "nomura.com"),
    "nordic capital":               ("FL",  "nordiccapital.com"),
    "norges bank":                  ("FL",  "nbim.no"),
    "northern trust":               ("FL",  "northerntrust.com"),
    "norton rose fulbright":        ("FL",  "nortonrosefulbright.com"),
    "nvidia":                       ("FL",  "nvidia.com"),
    "nuveen":                       ("FL",  "nuveen.com"),
    "nxp semiconductors":           ("FL",  "nxp.com"),
    "oak hill advisors":            ("FL",  "oakhilladvisors.com"),
    "oaknorth":                     ("FL",  "oaknorth.co.uk"),
    "oaktree capital management":   ("FL",  "oaktreecapital.com"),
    "oaktree":                      ("FL",  "oaktreecapital.com"),
    "ocado group":                  ("FL",  "ocado.com"),
    "oc&c":                         ("FL",  "occstrategy.com"),
    "octopus ventures":             ("FL",  "octopusventures.com"),
    "oppenheimer & co":             ("FL",  "oppenheimer.com"),
    "optiver":                      ("FL",  "optiver.com"),
    "oracle":                       ("FL",  "oracle.com"),
    "orbis":                        ("FL",  "orbis.com"),
    "osborne clarke":               ("FL",  "osborneclarke.com"),
    "oxera":                        ("FL",  "oxera.com"),
    "pa consulting":                ("FL",  "paconsulting.com"),
    "pai partners":                 ("FL",  "paipartners.com"),
    "paladin capital group":        ("FL",  "paladin.com"),
    "pantheon":                     ("FL",  "pantheon.com"),
    "pantheon capital management":  ("FL",  "pantheon.com"),
    "pareto securities":            ("FL",  "paretosec.com"),
    "partners group":               ("FL",  "partnersgroup.com"),
    "paul hastings":                ("FL",  "paulhastings.com"),
    "paypal":                       ("FL",  "paypal.com"),
    "pension insurance corporation": ("FL", "piculimited.com"),
    "pic":                          ("FL",  "piculimited.com"),
    "perella weinberg partners":    ("FL",  "pwpartners.com"),
    "pgim":                         ("FL",  "pgim.com"),
    "phoenix group":                ("FL",  "thephoenixgroup.com"),
    "pictet asset management":      ("FL",  "pictet.com"),
    "pimco":                        ("FL",  "pimco.com"),
    "pinsent masons":               ("FL",  "pinsentmasons.com"),
    "piper sandler":                ("FL",  "pipersandler.com"),
    "pitchbook":                    ("FL",  "pitchbook.com"),
    "pjt partners":                 ("FL",  "pjtpartners.com"),
    "pkf littlejohn":               ("FL",  "pkf-l.com"),
    "point72":                      ("FL",  "point72.com"),
    "polen capital":                ("FL",  "polencapital.com"),
    "principal asset management":   ("FL",  "principal.com"),
    "protiviti":                    ("FL",  "protiviti.com"),
    "psg equity":                   ("FL",  "psgequity.com"),
    "psp investments":              ("FL",  "investpsp.ca"),
    "putnam":                       ("FL",  "putnam.com"),
    "qatalyst partners":            ("FL",  "qatalyst.com"),
    "quadrature":                   ("FL",  "quadrature.com"),
    "qualcomm":                     ("FL",  "qualcomm.com"),
    "quantbot technologies":        ("FL",  "quantbot.com"),
    "quantcast":                    ("FL",  "quantcast.com"),
    "qube rt":                      ("FL",  "qube-rt.com"),
    "qube research & technologies": ("FL",  "qube-rt.com"),
    "rabobank":                     ("FL",  "rabobank.com"),
    "raine group":                  ("FL",  "rainegroup.com"),
    "raymond james":                ("FL",  "raymondjames.com"),
    "rbc capital markets":          ("FL",  "rbc.com"),
    "redington":                    ("FL",  "redington.co.uk"),
    "regions bank":                 ("FL",  "regions.com"),
    "revolut":                      ("FL",  "revolut.com"),
    "ripple":                       ("FL",  "ripple.com"),
    "roark capital group":          ("FL",  "roarkcapital.com"),
    "robeco":                       ("FL",  "robeco.com"),
    "rockefeller capital management": ("FL","rockco.com"),
    "rokos capital management":     ("FL",  "rokoscapital.com"),
    "roku":                         ("FL",  "roku.com"),
    "rolls-royce":                  ("FL",  "rolls-royce.com"),
    "rothesay":                     ("FL",  "rothesay.com"),
    "rothschild & co.":             ("FL",  "rothschildandco.com"),
    "rothschild & co":              ("FL",  "rothschildandco.com"),
    "rpc":                          ("FL",  "rpc.co.uk"),
    "rsm":                          ("FL",  "rsmuk.com"),
    "rsm us":                       ("FL",  "rsmus.com"),
    "rwe":                          ("FL",  "rwe.com"),
    "ryan specialty":               ("FL",  "ryanspecialty.com"),
    "saffery":                      ("FL",  "saffery.com"),
    "samsara":                      ("FL",  "samsara.com"),
    "sands capital":                ("FL",  "sandscapital.com"),
    "savills":                      ("FL",  "savills.com"),
    "schonfeld":                    ("FL",  "schonfeld.com"),
    "scotiabank":                   ("FL",  "scotiabank.com"),
    "sculptor capital management":  ("FL",  "sculptorcapital.com"),
    "seb group":                    ("FL",  "seb.se"),
    "severn trent":                 ("FL",  "severntrent.com"),
    "shakespeare martineau":        ("FL",  "shma.co.uk"),
    "shell":                        ("FL",  "shell.com"),
    "shoosmiths":                   ("FL",  "shoosmiths.com"),
    "siemens":                      ("FL",  "siemens.com"),
    "silversmith capital partners": ("FL",  "silversmithcapital.com"),
    "simon-kucher":                 ("FL",  "simon-kucher.com"),
    "sixth street":                 ("FL",  "sixthstreet.com"),
    "sky":                          ("FL",  "sky.uk"),
    "slate asset management":       ("FL",  "slateam.com"),
    "slb":                          ("FL",  "slb.com"),
    "smbc":                         ("FL",  "smbcgroup.com"),
    "snap":                         ("FL",  "snap.com"),
    "snyk":                         ("FL",  "snyk.io"),
    "societe generale":             ("FL",  "sgcib.com"),
    "société générale":             ("FL",  "sgcib.com"),
    "solomon partners":             ("FL",  "solomonpartners.com"),
    "sompo international":          ("FL",  "sompo-intl.com"),
    "sona asset management":        ("FL",  "sonaassetmanagement.com"),
    "soros fund management":        ("FL",  "soros.com"),
    "s&p global":                   ("FL",  "spglobal.com"),
    "spotify":                      ("FL",  "spotify.com"),
    "squarepoint capital":          ("FL",  "squarepointcap.com"),
    "squarespace":                  ("FL",  "squarespace.com"),
    "squire patton boggs":          ("FL",  "squirepb.com"),
    "starling bank":                ("FL",  "starlingbank.com"),
    "starwood capital group":       ("FL",  "starwood.com"),
    "state street":                 ("FL",  "ssga.com"),
    "stax":                         ("FL",  "stax.com"),
    "stephenson harwood":           ("FL",  "shlegal.com"),
    "stepstone group":              ("FL",  "stepstoneglobal.com"),
    "stifel":                       ("FL",  "stifel.com"),
    "st james's place":             ("FL",  "sjp.co.uk"),
    "st. james's place":            ("FL",  "sjp.co.uk"),
    "stone point capital":          ("FL",  "stonepointcapital.com"),
    "stonex":                       ("FL",  "stonex.com"),
    "stout":                        ("FL",  "stout.com"),
    "stripe":                       ("FL",  "stripe.com"),
    "summit partners":              ("FL",  "summitpartners.com"),
    "susquehanna international group": ("FL","sig.com"),
    "sig":                          ("FL",  "sig.com"),
    "swiss re":                     ("FL",  "swissre.com"),
    "td cowen":                     ("FL",  "tdcowen.com"),
    "temasek":                      ("FL",  "temasek.com.sg"),
    "teneo":                        ("FL",  "teneo.com"),
    "tesco":                        ("FL",  "tesco.com"),
    "texas capital bank":           ("FL",  "texascapitalbank.com"),
    "thales":                       ("FL",  "thalesgroup.com"),
    "the brattle group":            ("FL",  "brattle.com"),
    "the carlyle group":            ("FL",  "carlyle.com"),
    "the trade desk":               ("FL",  "thetradedesk.com"),
    "thought machine":              ("FL",  "thoughtmachine.net"),
    "tiaa":                         ("FL",  "tiaa.org"),
    "tikehau capital":              ("FL",  "tikehaucapital.com"),
    "tiktok":                       ("FL",  "tiktok.com"),
    "tishman speyer":               ("FL",  "tishmanspeyer.com"),
    "tlt":                          ("FL",  "tltsolicitors.com"),
    "tokio marine kiln":            ("FL",  "tmk.com"),
    "towerbrook capital partners":  ("FL",  "towerbrook.com"),
    "tower research capital":       ("FL",  "tower-research.com"),
    "tp icap":                      ("FL",  "tpicap.com"),
    "tradeweb":                     ("FL",  "tradeweb.com"),
    "trainline":                    ("FL",  "thetrainline.com"),
    "travers smith":                ("FL",  "traverssmith.com"),
    "triton":                       ("FL",  "triton.co.uk"),
    "t. rowe price":                ("FL",  "troweprice.com"),
    "trowers & hamlins":            ("FL",  "trowers.com"),
    "truist":                       ("FL",  "truist.com"),
    "tudor group":                  ("FL",  "tudor.com"),
    "turner & townsend":            ("FL",  "turnerandtownsend.com"),
    "two sigma":                    ("FL",  "twosigma.com"),
    "uber":                         ("FL",  "uber.com"),
    "uipath":                       ("FL",  "uipath.com"),
    "union square advisors":        ("FL",  "unionsquareadvisors.com"),
    "universal music group":        ("FL",  "umusic.com"),
    "uss":                          ("FL",  "uss.co.uk"),
    "uvimco":                       ("FL",  "uvimco.com"),
    "valor real estate partners":   ("FL",  "valorep.com"),
    "vanguard":                     ("FL",  "vanguard.com"),
    "verdane":                      ("FL",  "verdane.com"),
    "verisk":                       ("FL",  "verisk.com"),
    "virtu financial":              ("FL",  "virtu.com"),
    "visa":                         ("FL",  "visa.com"),
    "vista equity partners":        ("FL",  "vistaequitypartners.com"),
    "voloridge investment management": ("FL","voloridge.com"),
    "walker morris":                ("FL",  "walkermorris.co.uk"),
    "walter scott":                 ("FL",  "walter-scott.co.uk"),
    "warner bros. discovery":       ("FL",  "warnerbros.com"),
    "watson farley & williams":     ("FL",  "wfw.com"),
    "wfw":                          ("FL",  "wfw.com"),
    "weightmans":                   ("FL",  "weightmans.com"),
    "weiss asset management":       ("FL",  "weissasset.com"),
    "wellington management":        ("FL",  "wellington.com"),
    "welltower":                    ("FL",  "welltower.com"),
    "white & case":                 ("FL",  "whitecase.com"),
    "william blair":                ("FL",  "williamblair.com"),
    "wintermute":                   ("FL",  "wintermute.com"),
    "wipfli":                       ("FL",  "wipfli.com"),
    "wise":                         ("FL",  "wise.com"),
    "withers":                      ("FL",  "withersworldwide.com"),
    "womble bond dickinson":        ("FL",  "wbd-uk.com"),
    "wood mackenzie":               ("FL",  "woodmac.com"),
    "wtw":                          ("FL",  "willistowerswatson.com"),
    "willis towers watson":         ("FL",  "willistowerswatson.com"),
    "xtx markets":                  ("FL",  "xtxmarkets.com"),
    "zeus capital":                 ("FL",  "zeuscapital.co.uk"),
    "zs":                           ("FL",  "zs.com"),
    "zurich insurance":             ("FL",  "zurich.com"),
}
