use_default_settings:
  engines:
    keep_only:
      - bing
      - yahoo

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "inroad-searxng-internal"
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  formats:
    - html
    - json

engines:
  - name: bing
    engine: bing
    shortcut: bi
    disabled: false

  - name: yahoo
    engine: yahoo
    shortcut: yh
    disabled: false
