use_default_settings: true

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "inroad-searxng-internal"
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false

  - name: bing
    engine: bing
    shortcut: bi
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: d
    disabled: false

  - name: brave
    engine: brave
    shortcut: br
    disabled: false
